# SIMPLE Data Sets Test Report - via self-hosted runner
# Requires to install https://github.com/apps/artifact-ci
name: Build SIMPLE & Run Data Sets (Linux/MacOS)

on:
  push: {}

  schedule:
    # Runs at 00:00 UTC every day (Nightly)
    - cron: '0 0 * * *'

  # manually trigger for testing
  workflow_dispatch:

jobs:

  build_self_hosted:
    name: Build on self-hosted runner
    runs-on: [self-hosted, linux]
    timeout-minutes: 1440  # Increases the individual job limit to 24 hours
    steps:
      - uses: actions/checkout@v4

      - name: Run tests 
        run: |
             which simple_exec
             ./betagal.sh
             ./apof.sh
             ./make_report.sh betagal apof

      - name: Copy report
        run: mkdir -p build && cp report.html ./build// 

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: build/ 


