name: Run & Display SIMPLE Data Sets

on:
  #push: {}
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  SIMPLE_SYSTEMS: betagal apof proteasome trpm4 nanox

jobs:
  build_self_hosted:
    name: Build on self-hosted runner
    runs-on: [self-hosted, linux]
    timeout-minutes: 1440

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          export SIMPLE_EMAIL="my.name@uni.edu"
          export SIMPLE_QSYS="local"
          export SIMPLE_PATH=/home/meanapanedar2/programming/SIMPLE/build
          export PATH=${SIMPLE_PATH}/scripts:${SIMPLE_PATH}/bin:${PATH}
          which simple_exec
          echo $SIMPLE_PATH
          for system in $SIMPLE_SYSTEMS; do
            bash "./${system}.sh"
          done
          simple_test_exec test=simulated_workflow_6vxx 
          simple_test_exec test=simulated_workflow_1jxy 

      - name: Prepare report for Pages
        run: |
          ./make_report.sh $SIMPLE_SYSTEMS simulated_workflow_6vxx simulated_workflow_1jxy

      - name: Upload downloadable artifact
        uses: actions/upload-artifact@v4
        with:
          name: simple-data-sets-report
          path: build/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: build

  deploy_pages:
    name: Deploy report to GitHub Pages
    needs: build_self_hosted
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
